# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hitrans.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hitrans.proto',
  package='hitrans',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rhitrans.proto\x12\x07hitrans\"\x07\n\x05\x45mpty\"~\n\x0e\x43onfigurations\x12\x11\n\ttrans_url\x18\x01 \x01(\t\x12\x13\n\x0bsource_lang\x18\x02 \x01(\t\x12\x13\n\x0btarget_lang\x18\x03 \x01(\t\x12\x0f\n\x07\x61pi_key\x18\x04 \x01(\t\x12\r\n\x05model\x18\x05 \x01(\t\x12\x0f\n\x07version\x18\x06 \x01(\t\"A\n\rTextSelection\x12\x14\n\x0c\x64ouble_click\x18\x01 \x01(\x08\x12\x1a\n\x12\x66inished_selection\x18\x02 \x01(\x08\"L\n\x08Settings\x12.\n\x0etext_selection\x18\x01 \x01(\x0b\x32\x16.hitrans.TextSelection\x12\x10\n\x08shortcut\x18\x02 \x01(\t\"S\n\nConfigData\x12%\n\x04\x63onf\x18\x01 \x01(\x0b\x32\x17.hitrans.Configurations\x12\x1e\n\x03set\x18\x02 \x01(\x0b\x32\x11.hitrans.Settings2\xb1\x01\n\x07Hitrans\x12\x34\n\x10\x43reateConfigFile\x12\x0e.hitrans.Empty\x1a\x0e.hitrans.Empty\"\x00\x12\x36\n\rGetConfigFile\x12\x0e.hitrans.Empty\x1a\x13.hitrans.ConfigData\"\x00\x12\x38\n\x0fWriteConfigFile\x12\x13.hitrans.ConfigData\x1a\x0e.hitrans.Empty\"\x00\x62\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='hitrans.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=33,
)


_CONFIGURATIONS = _descriptor.Descriptor(
  name='Configurations',
  full_name='hitrans.Configurations',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trans_url', full_name='hitrans.Configurations.trans_url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_lang', full_name='hitrans.Configurations.source_lang', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_lang', full_name='hitrans.Configurations.target_lang', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='api_key', full_name='hitrans.Configurations.api_key', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model', full_name='hitrans.Configurations.model', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='hitrans.Configurations.version', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=161,
)


_TEXTSELECTION = _descriptor.Descriptor(
  name='TextSelection',
  full_name='hitrans.TextSelection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='double_click', full_name='hitrans.TextSelection.double_click', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='finished_selection', full_name='hitrans.TextSelection.finished_selection', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=228,
)


_SETTINGS = _descriptor.Descriptor(
  name='Settings',
  full_name='hitrans.Settings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text_selection', full_name='hitrans.Settings.text_selection', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shortcut', full_name='hitrans.Settings.shortcut', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=306,
)


_CONFIGDATA = _descriptor.Descriptor(
  name='ConfigData',
  full_name='hitrans.ConfigData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='conf', full_name='hitrans.ConfigData.conf', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='set', full_name='hitrans.ConfigData.set', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=391,
)

_SETTINGS.fields_by_name['text_selection'].message_type = _TEXTSELECTION
_CONFIGDATA.fields_by_name['conf'].message_type = _CONFIGURATIONS
_CONFIGDATA.fields_by_name['set'].message_type = _SETTINGS
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Configurations'] = _CONFIGURATIONS
DESCRIPTOR.message_types_by_name['TextSelection'] = _TEXTSELECTION
DESCRIPTOR.message_types_by_name['Settings'] = _SETTINGS
DESCRIPTOR.message_types_by_name['ConfigData'] = _CONFIGDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'hitrans_pb2'
  # @@protoc_insertion_point(class_scope:hitrans.Empty)
  ))
_sym_db.RegisterMessage(Empty)

Configurations = _reflection.GeneratedProtocolMessageType('Configurations', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGURATIONS,
  __module__ = 'hitrans_pb2'
  # @@protoc_insertion_point(class_scope:hitrans.Configurations)
  ))
_sym_db.RegisterMessage(Configurations)

TextSelection = _reflection.GeneratedProtocolMessageType('TextSelection', (_message.Message,), dict(
  DESCRIPTOR = _TEXTSELECTION,
  __module__ = 'hitrans_pb2'
  # @@protoc_insertion_point(class_scope:hitrans.TextSelection)
  ))
_sym_db.RegisterMessage(TextSelection)

Settings = _reflection.GeneratedProtocolMessageType('Settings', (_message.Message,), dict(
  DESCRIPTOR = _SETTINGS,
  __module__ = 'hitrans_pb2'
  # @@protoc_insertion_point(class_scope:hitrans.Settings)
  ))
_sym_db.RegisterMessage(Settings)

ConfigData = _reflection.GeneratedProtocolMessageType('ConfigData', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGDATA,
  __module__ = 'hitrans_pb2'
  # @@protoc_insertion_point(class_scope:hitrans.ConfigData)
  ))
_sym_db.RegisterMessage(ConfigData)



_HITRANS = _descriptor.ServiceDescriptor(
  name='Hitrans',
  full_name='hitrans.Hitrans',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=394,
  serialized_end=571,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateConfigFile',
    full_name='hitrans.Hitrans.CreateConfigFile',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetConfigFile',
    full_name='hitrans.Hitrans.GetConfigFile',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_CONFIGDATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='WriteConfigFile',
    full_name='hitrans.Hitrans.WriteConfigFile',
    index=2,
    containing_service=None,
    input_type=_CONFIGDATA,
    output_type=_EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HITRANS)

DESCRIPTOR.services_by_name['Hitrans'] = _HITRANS

# @@protoc_insertion_point(module_scope)
