# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import hitrans_pb2 as hitrans__pb2


class HitransStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateConfigFile = channel.unary_unary(
        '/hitrans.Hitrans/CreateConfigFile',
        request_serializer=hitrans__pb2.Empty.SerializeToString,
        response_deserializer=hitrans__pb2.Empty.FromString,
        )
    self.GetConfigFile = channel.unary_unary(
        '/hitrans.Hitrans/GetConfigFile',
        request_serializer=hitrans__pb2.Empty.SerializeToString,
        response_deserializer=hitrans__pb2.ConfigData.FromString,
        )
    self.WriteConfigFile = channel.unary_unary(
        '/hitrans.Hitrans/WriteConfigFile',
        request_serializer=hitrans__pb2.ConfigData.SerializeToString,
        response_deserializer=hitrans__pb2.Empty.FromString,
        )


class HitransServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateConfigFile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetConfigFile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def WriteConfigFile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HitransServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateConfigFile': grpc.unary_unary_rpc_method_handler(
          servicer.CreateConfigFile,
          request_deserializer=hitrans__pb2.Empty.FromString,
          response_serializer=hitrans__pb2.Empty.SerializeToString,
      ),
      'GetConfigFile': grpc.unary_unary_rpc_method_handler(
          servicer.GetConfigFile,
          request_deserializer=hitrans__pb2.Empty.FromString,
          response_serializer=hitrans__pb2.ConfigData.SerializeToString,
      ),
      'WriteConfigFile': grpc.unary_unary_rpc_method_handler(
          servicer.WriteConfigFile,
          request_deserializer=hitrans__pb2.ConfigData.FromString,
          response_serializer=hitrans__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'hitrans.Hitrans', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
