# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protos import secondrpc_pb2 as protos_dot_secondrpc__pb2


class SecondRpcStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.PopUp = channel.unary_unary(
        '/secondrpc.SecondRpc/PopUp',
        request_serializer=protos_dot_secondrpc__pb2.PopData.SerializeToString,
        response_deserializer=protos_dot_secondrpc__pb2.Empty.FromString,
        )


class SecondRpcServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def PopUp(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SecondRpcServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'PopUp': grpc.unary_unary_rpc_method_handler(
          servicer.PopUp,
          request_deserializer=protos_dot_secondrpc__pb2.PopData.FromString,
          response_serializer=protos_dot_secondrpc__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'secondrpc.SecondRpc', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
